'use server';import { prisma } from '@/lib/prisma';import { attendanceSchema,claimSchema,generateSchema,leaderSchema,searchSchema,uuidSchema } from '@/lib/validators';import { requireAdmin,requireLeader } from '@/lib/auth';import { randomUUID } from 'crypto';import bcrypt from 'bcryptjs';import { revalidatePath } from 'next/cache';
export async function claimCard(_:any,fd:FormData){const x=claimSchema.safeParse({uuid:fd.get('uuid'),fullName:fd.get('fullName')});if(!x.success)return {error:x.error.issues[0].message};try{await prisma.$transaction(async tx=>{const card=await tx.card.findUnique({where:{uuid:x.data.uuid}});if(!card)throw new Error('Card not found');if(card.ownerId)throw new Error('This card is already claimed');const user=await tx.user.create({data:{fullName:x.data.fullName}});await tx.card.update({where:{id:card.id},data:{ownerId:user.id}});await tx.activityLog.create({data:{cardId:card.id,userName:user.fullName,action:'CLAIMED'}})});revalidatePath(`/card/${x.data.uuid}`);return {ok:true}}catch(e:any){return {error:e.message}}}
export async function setAttendance(_:any,fd:FormData){const s=await requireLeader();const x=attendanceSchema.parse({cardId:fd.get('cardId'),attendanceNumber:fd.get('attendanceNumber'),checked:fd.get('checked')==='true'});const field=`attendance${x.attendanceNumber}` as any;const card=await prisma.card.update({where:{id:x.cardId},data:{[field]:x.checked},include:{owner:true}});await prisma.activityLog.create({data:{leaderId:s.leaderId,cardId:card.id,userName:card.owner?.fullName,attendanceNumber:x.attendanceNumber,action:x.checked?'CHECKED':'UNCHECKED'}});revalidatePath('/leader');revalidatePath(`/card/${card.uuid}`);return {ok:true}}
export async function generateCards(_:any,fd:FormData){await requireAdmin();const {count}=generateSchema.parse({count:fd.get('count')});await prisma.card.createMany({data:Array.from({length:count},()=>({uuid:randomUUID()}))});revalidatePath('/admin');return {ok:true}}
export async function createLeader(_:any,fd:FormData){await requireAdmin();const x=leaderSchema.parse({username:fd.get('username'),password:fd.get('password')});const l=await prisma.leader.create({data:{username:x.username,passwordHash:await bcrypt.hash(x.password,12)}});await prisma.activityLog.create({data:{leaderId:l.id,action:'LEADER_CREATED'}});revalidatePath('/admin');return {ok:true}}
export async function adminResetCard(cardId:string,type:'owner'|'attendance'|'delete'){await requireAdmin();if(type==='owner'){await prisma.card.update({where:{id:cardId},data:{ownerId:null}});await prisma.activityLog.create({data:{cardId,action:'CARD_RESET'}})}if(type==='attendance'){await prisma.card.update({where:{id:cardId},data:{attendance1:false,attendance2:false,attendance3:false,attendance4:false}});await prisma.activityLog.create({data:{cardId,action:'ATTENDANCE_RESET'}})}if(type==='delete'){await prisma.card.delete({where:{id:cardId}});await prisma.activityLog.create({data:{action:'CARD_DELETED',metadata:{cardId}}})}revalidatePath('/admin')}
export async function deleteLeader(id:string){await requireAdmin();await prisma.leader.delete({where:{id}});await prisma.activityLog.create({data:{action:'LEADER_DELETED',metadata:{id}}});revalidatePath('/admin')}
export async function toggleLeader(id:string,enabled:boolean){await requireAdmin();await prisma.leader.update({where:{id},data:{enabled}});await prisma.activityLog.create({data:{leaderId:id,action:enabled?'LEADER_ENABLED':'LEADER_DISABLED'}});revalidatePath('/admin')}
export async function searchCards(form:FormData){const x=searchSchema.parse({q:form.get('q')||'',status:form.get('status')||'all',count:form.get('count')||undefined});return prisma.card.findMany({where:{AND:[x.q?{OR:[{uuid:{contains:x.q,mode:'insensitive'}},{owner:{fullName:{contains:x.q,mode:'insensitive'}}}]}:{},x.status==='claimed'?{ownerId:{not:null}}:x.status==='unclaimed'?{ownerId:null}:x.status==='complete'?{attendance1:true,attendance2:true,attendance3:true,attendance4:true}:{},x.count!==undefined?{AND:Array.from({length:4},(_,i)=>({[`attendance${i+1}`]:i<x.count!})) as any}:{}]},include:{owner:true},take:50,orderBy:{createdAt:'desc'}})}
